name: Auto-Merge
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  enable-auto-merge:
    name: Enable Auto-Merge
    uses: zingimmick/.github/.github/workflows/auto-merge.yml@reusable-workflow
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

