name: Split Tests

on:
  pull_request:
  push:
    branches:
      - master
      - '[0-9]+.x'

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:
  split-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - china-administrative-divisions-laravel
          - laravel-eloquent-blameable
          - laravel-eloquent-images
          - laravel-eloquent-tags

    name: Split Tests of ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: shivammathur/setup-php@2.26.0

      - uses: ramsey/composer-install@v2

      - run: vendor/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package }}/composer.json --ansi

      - run: composer update --no-progress --ansi --working-dir packages/${{ matrix.package }}

      - working-directory: packages/${{ matrix.package }}
        run: vendor/bin/phpunit
