name: Split Tests

on:
  pull_request:
  push:
    branches:
      - master
      - '[0-9]+.x'

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:
  provide-packages-json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: shivammathur/setup-php@2.24.0

      - uses: ramsey/composer-install@v2

      # get package json list
      - id: output_data
        run: echo "matrix=$(vendor/bin/monorepo-builder packages-json --tests)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split-tests:
    needs: provide-packages-json

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.provide-packages-json.outputs.matrix )}}

    name: Split Tests of ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: shivammathur/setup-php@2.24.0

      - uses: ramsey/composer-install@v2

      - run: vendor/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package }}/composer.json --ansi

      - run: composer update --no-progress --ansi --working-dir packages/${{ matrix.package }}

      - working-directory: packages/${{ matrix.package }}
        run: vendor/bin/phpunit
