name: Split Monorepo

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  provide-packages-json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    # see https://stackoverflow.com/a/62953566/1348344
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      # required for matrix of packages set
      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: 7.4
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split:
    needs: provide-packages-json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide-packages-json.outputs.matrix)}}

    name: Monorepo Split of ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - run: |
          SHA1=$(git subtree split --prefix=packages/${{ matrix.package }} -q)
          git push https://zingimmick:${{ secrets.ACCESS_TOKEN }}@github.com/zingimmick/${{ matrix.package }}.git "$SHA1:$GITHUB_REF" -f
