name: Split Monorepo

on:
  push:
    branches:
      - master
      - '[0-9]+.x'
    tags:
      - '*'

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - china-administrative-divisions-laravel
          - laravel-eloquent-blameable
          - laravel-eloquent-images
          - laravel-eloquent-tags

    name: Monorepo Split of ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - run: |
          SHA1=$(git subtree split --prefix=packages/${{ matrix.package }} -q)
          git push https://zingimmick:${{ secrets.ACCESS_TOKEN }}@github.com/zingimmick/${{ matrix.package }}.git "$SHA1:$GITHUB_REF" -f
