name: Split Tag

on:
  push:
    # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
    tags:
      - '*'

jobs:
  provide-packages-json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    # see https://stackoverflow.com/a/62953566/1348344
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      # required for matrix of packages set
      - uses: shivammathur/setup-php@2.11.0
        with:
          php-version: 7.4
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split-tag:
    needs: provide-packages-json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide-packages-json.outputs.matrix)}}

    name: Split tag of ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v2.3.4

      - id: get-current-tag
        uses: zingimmick/github-action-get-current-tag@v1

      # Uses an action in the root directory
      - uses: symplify/github-action-monorepo-split@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'zingimmick'
          split-repository-name: '${{ matrix.package }}'
          tag: ${{ steps.get-current-tag.outputs.tag }}
          branch: master
          user-email: zingimmick@outlook.com
          user-name: zingimmick
